buildscript {
    ext.kotlin_version = '1.4.32'
    ext.android_gradle_build_version = '7.2.1'
    repositories {
        google()
        mavenCentral()
        // jcenter()
        maven {
            url "https://oss.sonatype.org/content/repositories/snapshots"
        }
        maven {
            url "https://plugins.gradle.org/m2/"
        }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:$android_gradle_build_version"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

