.PHONY: artifacts assemble upload publish version

GRADLE:=gradlew
GITNAME=$(shell ${GRADLE} app:androidGitVersionName --quiet)
artifacts: assemble upload

assemble:
	${GRADLE} clean assemble assembleEncrypted

version:
	${GRADLE} androidGitVersion

upload: version
	(cd app/build/outputs && scp -r apk ssh.mpcjanssen.nl:/var/www/html/artifacts/${GITNAME})


publish:
	${GRADLE} clean publishEncryptedRelease
