name: CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5
      - name: "Run build"
        #      run: ./gradlew assembleEncryptedDebug
        run: ./gradlew assembleDebug
      - name: "Save output artifacts"
        uses: actions/upload-artifact@v4
        with:
          name: apks
          path: app/build/outputs/apk
